<a href="https://colab.research.google.com/github/shivam003a/DataStructure/blob/master/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# importing Librabry
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as F

# matrix in numpy
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

# Numpy array to Tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

# Creating Tensor DataSet
train_ds = TensorDataset(inputs, targets)

# DataLoader
train_dl = DataLoader(train_ds, 5, shuffle=True)

# Setting up Linear Regression with weights and Biases
model = nn.Linear(3,2)

# Loss Function
loss_fn = F.mse_loss

# Optimizers to optimize the value of weights amd biases
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Training the model
for epochs in range(1000):
  for xb, yb in train_dl:
    preds = model(xb)
    loss = loss_fn(preds,yb)
    loss.backward()
    opt.step()
    opt.zero_grad()
  if (epochs+1) % 10 == 0:
    print('Epoch [{}/{}], Loss: {:.4f}'.format(epochs+1, 100, loss.item()))


Epoch [10/100], Loss: 723.0515
Epoch [20/100], Loss: 294.2465
Epoch [30/100], Loss: 62.2550
Epoch [40/100], Loss: 151.5657
Epoch [50/100], Loss: 42.5321
Epoch [60/100], Loss: 58.1883
Epoch [70/100], Loss: 52.6681
Epoch [80/100], Loss: 59.3688
Epoch [90/100], Loss: 31.6315
Epoch [100/100], Loss: 27.2206
Epoch [110/100], Loss: 23.5719
Epoch [120/100], Loss: 21.8105
Epoch [130/100], Loss: 23.5716
Epoch [140/100], Loss: 13.8371
Epoch [150/100], Loss: 19.2982
Epoch [160/100], Loss: 8.1952
Epoch [170/100], Loss: 13.3127
Epoch [180/100], Loss: 4.0984
Epoch [190/100], Loss: 9.8944
Epoch [200/100], Loss: 4.9881
Epoch [210/100], Loss: 6.7010
Epoch [220/100], Loss: 11.8628
Epoch [230/100], Loss: 9.7296
Epoch [240/100], Loss: 6.5737
Epoch [250/100], Loss: 3.9685
Epoch [260/100], Loss: 9.1012
Epoch [270/100], Loss: 3.3512
Epoch [280/100], Loss: 7.4682
Epoch [290/100], Loss: 6.9174
Epoch [300/100], Loss: 5.8501
Epoch [310/100], Loss: 3.4358
Epoch [320/100], Loss: 4.2151
Epoch [330/100], Loss: 2.1226

In [22]:
# Comparing the Trained output to Oringinal Output
print(model(inputs))
print(targets)


tensor([[ 57.0598,  70.5229],
        [ 81.9142, 100.3065],
        [118.5240, 133.1917],
        [ 20.9235,  37.8586],
        [101.6413, 118.1425],
        [ 55.8078,  69.4361],
        [ 81.7439, 100.3640],
        [118.8006, 133.7670],
        [ 22.1756,  38.9454],
        [102.7231, 119.2868],
        [ 56.8895,  70.5804],
        [ 80.6622,  99.2197],
        [118.6943, 133.1342],
        [ 19.8418,  36.7143],
        [102.8933, 119.2293]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [23]:
# Preding the data for New set of Values
print(model(torch.Tensor([[75. , 63. , 44.]])))

tensor([[53.5361, 67.6045]], grad_fn=<AddmmBackward0>)
